title: HASAN TEZCAN
tagline:

# Authors documented under _data

# Change to true for Disqus comments
disqus:
  comments: true
  disqus_shortname: 'https-hasantezcan-dev'

google-ID: 'UA-80213386-1'

menu:
- {name: 'Blog', path: 'menu', url: 'blog.html'}
- {name: 'Hakkımda', path: 'menu', url: 'about.html'}

# Available social icons are powered by Font Awesome, so you can use any icon that they offer
social:
- {icon: 'github', link: 'https://www.github.com/hasantezcan'}
#- {icon: 'facebook', link: 'https://facebook.com/damian.boqunowicz'}
- {icon: 'twitter', link: 'https://twitter.com/hasantezcann'}
- {icon: 'linkedin', link: 'https://www.linkedin.com/in/hasantezcann/'}
- {icon: 'youtube', link: 'https://www.youtube.com/channel/UCiBmvCxN4uXqma5qyaPOFHA'}
- {icon: 'rss-square', link: 'feed.xml'}
